######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 16:35:40 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ventana.h \
    Tablero.h \
    Ficha.h \
    Mapa.h
FORMS += Ventana.ui
SOURCES += Main.cpp Ventana.cpp \
    Tablero.cpp \
    Ficha.cpp \
    Mapa.cpp






